keys = [
  'cmd-j',
  'cmd-k',
  'cmd-,',
  'cmd-u',
  'cmd-e',
  'cmd-o',
  'cmd-q',
  'cmd-k alt-cmd-w',
  'cmd-k cmd-down',
  'cmd-k cmd-left',
  'cmd-k cmd-n',
  'cmd-k cmd-p',
  'cmd-k cmd-right',
  'cmd-k cmd-up',
  'cmd-k cmd-w',
  'cmd-k down',
  'cmd-k alt-cmd-w',
  'cmd-k up',
  'cmd-k right',
  'cmd-k left',
  'cmd-k cmd-l',
  'cmd-k cmd-u',
  'cmd+j',
  'cmd-k cmd-0',
  'cmd-k cmd-1',
  'cmd-k cmd-2',
  'cmd-k cmd-3',
  'cmd-k cmd-4',
  'cmd-k cmd-5',
  'cmd-k cmd-6',
  'cmd-k cmd-7',
  'cmd-k cmd-8',
  'cmd-k cmd-9',
  'cmd-k cmd-b',
  'cmd-k cmd-d',
  'cmd-k down',
  'cmd-k h',
  'cmd-k j',
  'cmd-k k',
  'cmd-k l',
  'cmd-k left',
  'cmd-k right',
  'cmd-k up'
]

for k in keys
  atom.keymap.keyBindings = atom.keymap.keyBindings.filter((binding, i) ->
    [k].indexOf(binding.keystrokes) == -1
  )
